[package]
name = "omekasy"
version = "1.0.0"
authors = ["ikanago <ikanago-dev@protonmail.com>"]
description = "Decorate alphanumeric characters in your input with various font; special characters in Unicode"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ikanago/omekasy"
edition = "2021"

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
crossterm = "0.23.2"

[profile.dev]
debug = 0

